package com.ardublock.translator.block;

import com.ardublock.translator.Translator;
import com.ardublock.translator.block.exception.SocketNullException;
import com.ardublock.translator.block.exception.SubroutineNotDeclaredException;

public class BotonEdukit extends TranslatorBlock
{
	public BotonEdukit(Long blockId, Translator translator, String codePrefix, String codeSuffix, String label)
	{
		super(blockId, translator, codePrefix, codeSuffix, label);
	}

	private final static String buttonFunction = "boolean ardublockDigitalReadAutogenerated(int pinNumber)\n" + 
			"{\n" + 
			"  pinMode(pinNumber, INPUT);\n" + 
			"  return digitalRead(pinNumber);\n" + 
			"}";
	
	@Override
	public String toCode() throws SocketNullException, SubroutineNotDeclaredException
	{
		
		translator.addDefinitionCommand(buttonFunction);
		
		TranslatorBlock translatorBlock = this.getRequiredTranslatorBlockAtSocket(0);
		
		String pinNumber = translatorBlock.toCode();
		
		if(pinNumber.equalsIgnoreCase("1")) {
			pinNumber = "2";
		}else {
			if(pinNumber.equalsIgnoreCase("2")) {
				pinNumber = "3";
			}else {
				if(pinNumber.equalsIgnoreCase("3")) {
					pinNumber = "4";
				}else {
					pinNumber = "2";
				}
			}
		}
		
		String ret = "\tardublockDigitalReadAutogenerated( "+pinNumber+" )";
		

		return codePrefix + ret + codeSuffix;
	}
	
}
